"""Error codes for scripts manager API."""

from enum import Enum


class ErrorCode(str, Enum):
    """Error codes for API responses."""

    # Validation errors (400)
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_FILENAME = "INVALID_FILENAME"
    INVALID_SCRIPT_CONTENT = "INVALID_SCRIPT_CONTENT"
    SCRIPT_MISSING_MAIN = "SCRIPT_MISSING_MAIN"
    INVALID_FOLDER_NAME = "INVALID_FOLDER_NAME"
    
    # Resource not found (404)
    FOLDER_NOT_FOUND = "FOLDER_NOT_FOUND"
    SCRIPT_NOT_FOUND = "SCRIPT_NOT_FOUND"
    PARENT_FOLDER_NOT_FOUND = "PARENT_FOLDER_NOT_FOUND"
    
    # Conflict errors (409)
    FOLDER_ALREADY_EXISTS = "FOLDER_ALREADY_EXISTS"
    SCRIPT_ALREADY_EXISTS = "SCRIPT_ALREADY_EXISTS"
    SCRIPT_EXISTS_REPLACE_REQUIRED = "SCRIPT_EXISTS_REPLACE_REQUIRED"
    
    # Permission errors (403)
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOLDER_OWNER = "NOT_FOLDER_OWNER"
    NOT_SCRIPT_OWNER = "NOT_SCRIPT_OWNER"
    NOT_ALL_OWNER = "NOT_ALL_OWNER"
    
    # Internal server errors (500)
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    FILE_SYSTEM_ERROR = "FILE_SYSTEM_ERROR"

